### Import libraries

In [1]:
import numpy as np
import pandas as pd

### Read CSV file

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/fendiirfan/Hoax_Detection_Microcredential_Associate_Data_Scientist/main/datasetHoax.csv')

In [3]:
df.head()

narasi  \
0  caler tryout radio talk show recently shared t...   
1  ythseluruh angota grup sesuai instruksi gubern...   
2  jokowi adalah presiden terbaik dalam sejarah b...   
3  maf mas dan mbak ini bukan politik tapi kenyat...   
4            kadrun jika lihat foto ini panas dingin   

                                               judul  label  
0  pemakaian masker menyebabkan penyakit legionaires      1  
1  instruksi gubernur jateng tentang penilangan b...      1  
2  foto jim rohn jokowi adalah presiden terbaik d...      1  
3  ini bukan politik tapi kenyatan pak jokowi ber...      1  
4       foto kadrun jika lihat foto ini panas dingin      1

In [4]:
df['label'].value_counts()

1    8189
0    1471
Name: label, dtype: int64

### Classifying hoax based on news title 

In [5]:
X = df['judul']
y = df['label']

In [6]:
X.shape

(9660,)

In [7]:
y.shape

(9660,)

### Spliting training and test data

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [9]:
y_train.head()

3332    0
4967    1
5363    1
4053    1
4071    0
Name: label, dtype: int64

# Machine Learning

In [10]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

vectorizer = TfidfVectorizer()
X_train_Vec = vectorizer.fit_transform(X_train)

X_test_Vec = vectorizer.transform(X_test)

print(X_train[0])
print(X_train_Vec[0].toarray())

pemakaian masker menyebabkan penyakit legionaires
[[0. 0. 0. ... 0. 0. 0.]]


### Building machine learning model

In [11]:
from sklearn import svm

clf_svm = svm.SVC()
clf_svm.fit(X_train_Vec, y_train)
clf_svm.predict(X_test_Vec[0])

array([1], dtype=int64)

### Model evaluation

In [12]:
from sklearn.metrics import classification_report, confusion_matrix

Y_pred = clf_svm.predict(X_test_Vec)

print(classification_report(y_test,Y_pred))

cm = confusion_matrix(y_test, Y_pred)

print('Confusion matrix for SVM\n', cm)

              precision    recall  f1-score   support

           0       0.89      0.54      0.67       448
           1       0.92      0.99      0.95      2450

    accuracy                           0.92      2898
   macro avg       0.91      0.76      0.81      2898
weighted avg       0.92      0.92      0.91      2898

Confusion matrix for SVM
 [[ 241  207]
 [  30 2420]]


In [13]:
test_set = ['besok tidak jadi kiamat, pemerintah sipakan penanganan pandemi']
new_test = vectorizer.transform(test_set)

clf_svm.predict(new_test)

array([1], dtype=int64)

# Save Model

In [14]:
import pickle

In [15]:
pickle.dump(vectorizer,open('tokenizer_SVM', 'wb'))

In [16]:
pickle.dump(clf_svm,open('SVM', 'wb'))